# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'SharedTogether' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SharedTogether
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Alamofire'
  
  pod 'GeoFire'
  
  pod 'KVNProgress'

end
